[package]
name = "rating-contract"
version = "1.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
soroban-sdk = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
rand = "0.8"
reputation-nft-contract = { path = "../reputation-nft-contract" }

[features]
testutils = ["soroban-sdk/testutils"]
